export interface IPublisherPromotionInList {
  id: number;
  product_id: number;
  show_order: number;
  created_id: number;
  created_date: string;
  updated_id: number;
  updated_date: string;
  title: string;
  price_type: string;
  status_code: string;
  ratings_code: string;
  synopsis_text: string;
  user_id: number;
  author_id: number;
  author_name: string;
  publish_regular_yn: "Y" | "N";
  publish_days: string;
  thumbnail_file_id: number;
  primary_genre_id: number;
  sub_genre_id: number;
  count_hit: number;
  count_cp_hit: number;
  count_recommend: number;
  count_bookmark: number;
  count_unbookmark: number;
  open_yn: "Y" | "N";
  approval_yn: "Y" | "N";
  monopoly_yn: "Y" | "N";
  contract_yn: "Y" | "N";
  single_regular_price: number;
  series_regular_price: number;
  sale_price: number;
  cp_company_name: string;
}

export interface IPublisherPromotion {
  id: number;
  product_id: number;
  show_order: number;
  created_id: number;
  created_date: string;
  updated_id: number;
  updated_date: string;
  title: string;
  price_type: string;
  product_type: string;
  status_code: string;
  ratings_code: string;
  synopsis_text: string;
  user_id: number;
  author_id: number;
  author_name: string;
  illustrator_id: string;
  illustrator_name: string;
  publish_regular_yn: string;
  publish_days: string;
  thumbnail_file_id: number;
  primary_genre_id: number;
  sub_genre_id: number;
  count_hit: number;
  count_cp_hit: number;
  count_recommend: number;
  count_bookmark: number;
  count_unbookmark: number;
  open_yn: string;
  approval_yn: string;
  monopoly_yn: string;
  contract_yn: string;
  paid_open_date: string;
  paid_episode_no: string;
  last_episode_date: string;
  isbn: string;
  uci: string;
  single_regular_price: number;
  series_regular_price: number;
  sale_price: number;
  apply_date: string;
}
