import AdminPopup from "@/components/common/AdminPopup";
import AuthInitializer from "@/components/common/AuthInitializer";
import Confirm from "@/components/common/Confirm";
import NavigationTracker from "@/components/common/NavigationTracker";
import Spinner from "@/components/common/Spinner";
import Toast from "@/components/common/Toast";
import WithNoSSR from "@/components/common/WithNoSSR";
import CacheStatusModal from "@/components/modal/CacheStatusModal";
import CacheUseModal from "@/components/modal/CacheUseModal";
import DonateModal from "@/components/modal/DonateModal";
import RentalStatusModal from "@/components/modal/RentalStatusModal";
import ReportReasonModal from "@/components/modal/ReportReasonModal";
import AiChatPanel from "@/components/recommendation/AiChatPanel";
import SearchModal from "@/components/search/SearchModal";
import ErrorBoundaryWrapper from "@/hooks/useErrorBoundary";
import ReactQueryProvider from "@/hooks/useReactQuery";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Suspense } from "react";
import "./globals.css";

const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
});

export const metadata: Metadata = {
  title: "라이크노벨",
  description: "Generated by likenovel",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.className}`}>
        <WithNoSSR>
          <ReactQueryProvider>
            <Suspense
              fallback={
                <div className="w-full h-screen flex justify-center items-center">
                  <Spinner />
                </div>
              }
            >
              <ErrorBoundaryWrapper>
                <AuthInitializer />
                <NavigationTracker />
                {children}
                <AiChatPanel />
                {modal}
                <div id="modal-root" />
                <Confirm />
                <Toast />
                <AdminPopup />
                <SearchModal />
                <CacheUseModal />
                <DonateModal />
                <CacheStatusModal />
                <RentalStatusModal />
                <ReportReasonModal />
              </ErrorBoundaryWrapper>
            </Suspense>
          </ReactQueryProvider>
        </WithNoSSR>
      </body>
    </html>
  );
}
