version: '3.8'

services:
  likenovel-user:
    image: aiaracorp1/likenovel-user:production
    container_name: likenovel-user-production
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
