export interface IHourlyInflow {
  product_id: number;
  title: string;
  price_type: string;
  product_type: string | null;
  status_code: string;
  ratings_code: string;
  synopsis_text: string;
  user_id: number;
  author_id: number;
  author_name: string;
  illustrator_id: number | null;
  illustrator_name: string | null;
  publish_regular_yn: "Y" | "N";
  publish_days: string;
  thumbnail_file_id: number;
  primary_genre_id: number;
  sub_genre_id: number;
  count_hit: number;
  count_cp_hit: number;
  count_recommend: number;
  count_bookmark: number;
  count_unbookmark: number;
  open_yn: "Y" | "N";
  approval_yn: "Y" | "N";
  monopoly_yn: "Y" | "N";
  contract_yn: "Y" | "N";
  paid_open_date: string | null;
  paid_episode_no: number | null;
  last_episode_date: string | null;
  isbn: string | null;
  uci: string | null;
  single_regular_price: number;
  series_regular_price: number;
  sale_price: number;
  apply_date: string | null;
  created_id: number;
  created_date: string;
  updated_id: number;
  updated_date: string;
}

export interface IHourlyInflowDetail {
  hour: number;
  total_view_count: number;
  total_payment_count: number;
  male_view_count: number;
  female_view_count: number;
  male_payment_count: number;
  female_payment_count: number;
  male_20_under_payment_count: number;
  male_30_payment_count: number;
  male_40_payment_count: number;
  male_50_payment_count: number;
  male_60_over_payment_count: number;
  female_20_under_payment_count: number;
  female_30_payment_count: number;
  female_40_payment_count: number;
  female_50_payment_count: number;
  female_60_over_payment_count: number;
  male_20_under_view_count: number;
  male_30_view_count: number;
  male_40_view_count: number;
  male_50_view_count: number;
  male_60_over_view_count: number;
  female_20_under_view_count: number;
  female_30_view_count: number;
  female_40_view_count: number;
  female_50_view_count: number;
  female_60_over_view_count: number;
}
