import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";
import AuthGuard from "@/components/common/AuthGuard";
import ReactQueryProvider from "@/hooks/useReactQuery";
import { Suspense } from "react";
import Spinner from "@/components/common/Spinner";
import ErrorBoundaryWrapper from "@/hooks/useErrorBoundary";
import WithNoSSR from "@/components/common/WithNoSSR";
import { useProfile } from "@/hooks/useProfile";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WithNoSSR>
          <ReactQueryProvider>
            <AuthGuard>
              <Suspense
                fallback={
                  <div className="w-full h-screen flex justify-center items-center">
                    <Spinner />
                  </div>
                }
              >
                <ErrorBoundaryWrapper>{children}</ErrorBoundaryWrapper>
              </Suspense>
            </AuthGuard>
          </ReactQueryProvider>
        </WithNoSSR>
      </body>
    </html>
  );
}
